/// <reference path="../bower_components/DefinitelyTyped/angularjs/angular.d.ts"/>
/// <reference path="../bower_components/DefinitelyTyped/angular-ui-router/angular-ui-router.d.ts" />
/// <reference path="../bower_components/DefinitelyTyped/angular-dialog-service/angular-dialog-service.d.ts" />
/// <reference path="../bower_components/DefinitelyTyped/angularjs/angular-resource.d.ts"/>
/// <reference path="../bower_components/DefinitelyTyped/angular-material/angular-material.d.ts"/>
/// <reference path="../bower_components/DefinitelyTyped/angular-translate/angular-translate.d.ts"/>
/// <reference path="../bower_components/DefinitelyTyped/angular-dynamic-locale/angular-dynamic-locale.d.ts"/>
/// <reference path="../bower_components/DefinitelyTyped/cordova/cordova.d.ts" />
/// <reference path="../bower_components/DefinitelyTyped/Q/Q.d.ts" />
